language: csharp
mono: none
sudo: required
services:
    - docker
branches:
    only:
        - master
before_script:
    - chmod -R a+x scripts
script:
    - "./scripts/travis-build.sh"
after_success:
    - "./scripts/travis-docker-publish.sh"
notifications:
    email:
        on_success: never
        on_failure: never
