language: csharp
mono: none
sudo: required
services:
    - docker
branches:
    only:
        - master
before_script:
    - chmod -R a+x scripts
script:
    - './scripts/travis-build.sh'
after_success:
    - './scripts/travis-docker-publish.sh'
notifications:
    email: false
    slack:
        secure: AqUEirmT/zGl05KhHTSK8bSEzPAoGpI9cvvZvDZ03BnMX5IXCV6SR790ML4ahNFOZTcT9PdFFTE6qFkLrKgIk5bzJ/XVqIDWnd+OYFA6OIW7uhYoRR+cg6XKVYcm++xhW3vZszj9DZmjZvMenfYeq3RjkJC1tamL9poVg3Eg2m+jCSOpEDGvgUnSnuAQs50VPBb5VTzcKkk95wHy+mT2DmTF8tuPg3pqmJzWAcWJRAfaqQ5CzTnXcsMbjji637E9Tn4F+qnz6+htLbozYcZGCLTw4tzp05/nQDu47PHlMqILUsSR4NsZSUoNVvOq2ekkAfQymN2qgCEINc2KX7K4ZHl5jJ7+NNa+k+MbG/4rBpj5H681CIYrSuQfHRSEA/0SgLUtrsmwqp0XUT7PB93g4thP+HY5ZY2w0qQuTfUeLICkX9ShxrEhd6IbSWroUkNnnHkZaTp267jTjSiNT3mCpRbSsKMqZRzmxABisjuJkyHO8VGLQ8n5k3WrEl90mhG3UAjCR1ijBaF//7bl5Ta/ptr2FSBHTZuPjKFGSsvEhE1SlYeybm1Ll8fVVTlvXahrRcL1GEzVsailSzYtdxwrh8s4oSHEZM+TIM4JT2Lg+pd9JnJxHvVxO1L3q/wGvqQPq7L3O7nJnXo290kDEoaxAB/rnWzOnkWjMhBU8xCmI3A=
        on_pull_requests: false
