language: csharp
mono: none
sudo: required
services:
    - docker
branches:
    only:
        - master
        - dev
before_script:
    - chmod -R a+x scripts
script:
    - "./scripts/travis-build.sh"
after_success:
    - "./scripts/travis-docker-publish.sh"
notifications:
    email: false
    slack:
        secure: j65VW5dYQ2cJO94I7CRYIXo/aRAf8ZilAPmJLH5V2rkJ/VoXY9QDPFwoIJ5GLDXFhs3S/ojgb1YUrmvRDfsQrcO9gsgEhSHmTUHiscJ/EHsynTUvgiczEsCp1+tlN4sdw9y86+SE4O3A32T2hImhC/gu6EVNnelC7OxPgKcgXA67iKYrB051LJowPEM2I2Kt3qC8VJOWjIKFpinE3pdV3A4ZP4MbrCW4kFKmbEHGLouBbEN4XUot3g1Iqwm8DBPLy8eVKXrIkaTSNBoKo1NTJikVXYhyKaEzgi9NDDL+RaoqH8PmCwd2d72DBGbFlRJr7+YzNMlscLgvIBHKbKwlRwopQBFNMEpQV19/H79xEK8QN9V+mAl52Jeye21FNsEofX2gB0GxqULQYInJ/lLa3N+iM0ZY7M/RjueA+V9n2khSESaiBO2EY1Y3SXWSB2eHYEQT1YsyVhjEuOyFQXre1Ve/V94wt3Bt3DcVuWF+R+bHslYCBeRPuGNqCfRE0i+ih84Yld9nlNtRXL10TtmOLi+ceB4itn5b4pz40bIeT1InBj5EqPze3YTCKUYCRFivwCBuT4AoJEIq1sfl/2wiE6GRKex2EPW1D+ZdyHmHwA4bykZhD8lcrgnS2KXGXWN6CzQ5/aLpc1Y95ZIvo6Cl4atdJFKCKQiKKDCfsJB0IDA=
        on_pull_requests: false
